spring:
  application:
    name:
      SpringPrak14

  datasource:
    url: jdbc:postgresql://localhost:5432/MireaCourse
    username: postgres
    password: aks
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl-auto: update
    show-sql: true

export:
  directory: src/main/java/com/ldf/springprak14/Data
